#!/usr/bin/env bash
# ============================================================================
# Vass — first-install script.
#
# Use on a fresh server. Idempotent: re-running is safe and skips already-
# completed steps.
#
# What it does:
#   1. Checks prerequisites (docker, docker compose plugin)
#   2. Generates a secure .env file (if missing)
#   3. Prompts for the public-facing URL
#   4. Builds + starts all containers
#   5. Runs database migrations
#   6. Creates the first admin user (interactive)
#
# Usage:
#   chmod +x install.sh
#   ./install.sh
# ============================================================================

set -euo pipefail

# -------- Pretty output helpers --------
c_red()    { printf '\033[31m%s\033[0m\n' "$*"; }
c_green()  { printf '\033[32m%s\033[0m\n' "$*"; }
c_yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
c_blue()   { printf '\033[36m%s\033[0m\n' "$*"; }
step()     { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
fail()     { c_red "✗ $*"; exit 1; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# ============================================================================
# 1. Prerequisites
# ============================================================================
step "Checking prerequisites"

command -v docker >/dev/null 2>&1 || fail "docker not found. Install Docker first: https://docs.docker.com/engine/install/"

if ! docker compose version >/dev/null 2>&1; then
  fail "'docker compose' plugin not found. Update Docker to v20.10+ which ships with Compose v2."
fi

if ! docker info >/dev/null 2>&1; then
  fail "Docker daemon is not responding. Is the service running? Try: sudo systemctl start docker"
fi

c_green "✓ docker and docker compose are working"

# Check the host ports we want aren't already taken
for port in 3030 4040; do
  if ss -tln 2>/dev/null | grep -qE ":${port}\b" || \
     netstat -tln 2>/dev/null | grep -qE ":${port}\b"; then
    c_yellow "⚠ Port ${port} is already in use on this host."
    c_yellow "   If it's an old Vass install, that's fine — continue."
    c_yellow "   Otherwise edit docker-compose.yml to use different host ports."
    read -rp "   Continue anyway? [y/N] " ans
    [[ "${ans:-N}" =~ ^[Yy]$ ]] || exit 1
  fi
done

# ============================================================================
# 2. Generate .env if missing
# ============================================================================
step "Setting up .env"

if [ -f .env ]; then
  c_blue "  .env already exists — keeping it."
  c_blue "  (Delete it manually if you want a clean re-install.)"
else
  c_blue "  No .env found — generating one with fresh secrets."

  # Strong random strings. We use /dev/urandom + base64 + tr to keep it
  # portable (no openssl dependency). 48 bytes → 64-char base64 → strip
  # any URL-unsafe chars → take the first 48.
  gen_secret() {
    head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c 48
  }

  POSTGRES_PASSWORD=$(gen_secret)
  SESSION_SECRET=$(gen_secret)

  # Public-facing URL where users access Vass. Used for the OAuth redirect
  # URI (must match exactly what's registered in the Meta App).
  c_blue ""
  c_blue "  What's the public URL where Vass will be reachable?"
  c_blue "  e.g. https://vass.example.com    (no trailing slash, https in prod)"
  c_blue "  Press Enter to use http://localhost:3030 for local-only setup."
  read -rp "  URL: " FRONTEND_URL
  FRONTEND_URL="${FRONTEND_URL:-http://localhost:3030}"

  # NEXT_PUBLIC_API_URL is what the frontend uses to call the backend.
  # In production this is the same host with the /api prefix (the reverse
  # proxy strips /api before forwarding to the backend container).
  # For pure local setup with no reverse proxy, it talks to backend directly.
  if [[ "$FRONTEND_URL" == "http://localhost:3030" ]]; then
    NEXT_PUBLIC_API_URL="http://localhost:4040"
  else
    NEXT_PUBLIC_API_URL="${FRONTEND_URL}/api"
  fi

  cat > .env <<ENV
# Vass — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Treat this file as a secret. Keep it out of git.

# ---- Postgres ----
POSTGRES_USER=vass
POSTGRES_DB=vass
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ---- Backend secrets ----
# SESSION_SECRET is also used to derive the AES-256-GCM key that encrypts
# stored Meta App secrets and access tokens. NEVER rotate this on a live
# install — all stored encrypted values will become unrecoverable.
SESSION_SECRET=${SESSION_SECRET}

# ---- URLs ----
# Public URL users hit in their browser. OAuth callbacks redirect here.
FRONTEND_URL=${FRONTEND_URL}
# URL the frontend uses to call the backend. Behind a reverse proxy
# rewriting /api/* → backend:4000, this is \${FRONTEND_URL}/api.
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# ---- Misc ----
NODE_ENV=production
ENV
  chmod 600 .env
  c_green "  ✓ Generated .env (chmod 600)"
  c_yellow "  ⚠ Back up this file. SESSION_SECRET cannot be regenerated without"
  c_yellow "    losing access to all stored encrypted secrets."
fi

# ============================================================================
# 3. Defensive: BusyBox sed -u fix for supervise.sh
# ============================================================================
# Some Alpine images ship BusyBox sed which doesn't support -u (line-buffered).
# The patch installer already does this; do it here too.
if [ -f backend/supervise.sh ]; then
  sed -i 's| sed -u | sed |g' backend/supervise.sh
  chmod +x backend/supervise.sh
fi

# ============================================================================
# 4. Build + start the stack
# ============================================================================
step "Building containers (this takes a few minutes on first install)"
docker compose build

step "Starting all services"
docker compose up -d

# ============================================================================
# 5. Wait for backend, run migrations
# ============================================================================
step "Waiting for backend to be reachable"
for i in $(seq 1 60); do
  if docker compose exec -T backend echo ok >/dev/null 2>&1; then
    c_green "  ✓ Backend container reachable after ${i}s"
    break
  fi
  sleep 1
  if [ "$i" = 60 ]; then
    c_red "  ✗ Backend never came up. Check logs:"
    docker compose logs --tail=40 backend
    exit 2
  fi
done

step "Running database migrations"
if ! docker compose exec -T backend npm run migrate; then
  c_red ""
  c_red "✗ Migrations FAILED. Vass will not work until they apply."
  c_red ""
  c_red "Recent backend logs:"
  docker compose logs --tail=30 backend
  exit 3
fi
c_green "  ✓ Migrations applied"

# ============================================================================
# 6. Create the first admin user (only if no users exist yet)
# ============================================================================
step "Checking for existing admin user"
USER_COUNT=$(docker compose exec -T postgres psql -U vass -d vass -tAc \
  "SELECT COUNT(*) FROM users WHERE deleted_at IS NULL;" 2>/dev/null || echo "?")

if [ "$USER_COUNT" = "0" ]; then
  c_blue "  No users yet. Create the first admin:"
  read -rp "  Admin email:    " ADMIN_EMAIL
  read -rp "  Admin name:     " ADMIN_NAME
  read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD
  echo

  if [ ${#ADMIN_PASSWORD} -lt 8 ]; then
    fail "Password must be at least 8 characters."
  fi

  # Pass via env so the password never lands in a process listing.
  docker compose exec -T \
    -e VASS_EMAIL="$ADMIN_EMAIL" \
    -e VASS_NAME="$ADMIN_NAME" \
    -e VASS_PASSWORD="$ADMIN_PASSWORD" \
    -e VASS_ROLE="admin" \
    backend npm run create-user

  c_green "  ✓ Admin user created"
else
  c_blue "  $USER_COUNT user(s) already exist — skipping admin creation."
  c_blue "  To add more, sign in as an admin and use the Team page."
fi

# ============================================================================
# Done
# ============================================================================
echo
c_green "================================================================"
c_green "  Vass is up."
c_green "================================================================"
echo
echo "  Frontend:  ${FRONTEND_URL:-http://localhost:3030}"
echo "  Backend:   http://localhost:4040  (only reachable from this host)"
echo
echo "  Tail logs:    docker compose logs -f"
echo "  Stop:         docker compose down       (preserves data)"
echo "  Stop + wipe:  docker compose down -v    (deletes the database)"
echo "  Update later: ./scripts/install-patch.sh <patch-zip>"
echo
if [[ "${FRONTEND_URL:-}" != "http://localhost:3030" ]]; then
  echo "  Reverse proxy:"
  echo "    Your reverse proxy should forward:"
  echo "      ${FRONTEND_URL}/      → 127.0.0.1:3030"
  echo "      ${FRONTEND_URL}/api/* → 127.0.0.1:4040 (stripping the /api prefix)"
  echo "    See README.md for nginx, Apache, and Caddy snippets."
fi
echo
echo "  Next: sign in at ${FRONTEND_URL:-http://localhost:3030}/login"
echo "        then configure Settings → Meta with your Meta App credentials."
echo
